### ISSUE TITLE
Return product images with product data

### ISSUE THREAD

**Issue by prionkor** [co-cart/cocart-get-cart-enhanced#15]
**Is this enhancement related to a problem? Please describe.**
When implementing the cart the enhanced data helps a lot but currently no images data is returned. If the response returns product thumbnail it would be easier to show them directly. 

**Describe alternatives you've considered**
Currently for images I have to call the product API to get this data which beats the purpose of this plugin.

**Comment by seb86** [comment]
Check the documentation @prionkor You will see how to get product thumbnail.
